imports:
- $import torch
- $import scripts
- $import scripts.net
- $import scripts.train
- $import scripts.transforms
- $import scripts.dataloaders

bundle_root: ./tutorials/model/IntegrationBundle
# ckpt_path: $@bundle_root + '/models/model_trained.pt'
ckpt_path: $@bundle_root + '/models/model.pt'

net:
  _target_: scripts.net.Net

# pretrained_weights_path: 

transforms: '$scripts.transforms.transform'

# dataloader: '$scripts.dataloaders.get_dataloader(True, @transforms)'
dataloader: '$scripts.dataloaders.datastore_dataloader(@train#dataset#data, @validate#dataset#data, @transforms)'

train:
  trainer:
    max_epochs: 3
  dataset:
    data: []

validate:
  dataset:
    data: []

# train:
# - $scripts.train.train(@net, @dataloader)
# - $torch.save(@net.state_dict(), './cifar_net.pth')

# trainer:
# - $scripts.train.train(@net, @dataloader)
# - $torch.save(@net.state_dict(), './cifar_net.pth')


run:
- $scripts.train.train(@net, @dataloader, @ckpt_path)
- $torch.save(@net.state_dict(), @ckpt_path)
