imports:
- $import scripts
- $import scripts.net
- $import scripts.inference
- $import scripts.transforms

# ckpt_path: './cifar_net.pth'

# input_dir: 'test_cifar10'
# input_files: '$sorted(glob.glob(@input_dir+''/*.*''))'

# device: '$torch.device(''cuda:0'')'

dropout: 0.1

network_def: 
- _target_: scripts.net.CustomSegformerModel

# transforms: '$scripts.transforms.transform'

image: $monai.utils.CommonKeys.IMAGE
pred: $monai.utils.CommonKeys.PRED

# pre_transforms: '$scripts.transforms.test_transform'

pre_transforms:
- _target_: LoadImaged
  keys: '@image'
  image_only: true
- _target_: EnsureChannelFirstd
  keys: 'image'
- _target_: NormalizeIntensityd
  keys: '@image'
  subtrahend: [0.522, 0.300, 0.167]
  divisor: [0.240, 0.189, 0.147]
  channel_wise: True

# pre_transforms:
# - _target_: LoadImaged
#   keys: '@image'
#   image_only: true
# - _target_: EnsureChannelFirstd
#   keys: '@image'
# - _target_: ScaleIntensityd
#   keys: '@image'
# - _target_: NormalizeIntensityd
#   keys: '@image'
#   subtrahend: [0.5, 0.5, 0.5]
#   divisor: [0.5, 0.5, 0.5]
#   channel_wise: True

# https://docs.monai.io/en/stable/transforms.html
# see above and ctrl+f for Activationsd
post_transforms:
- _target_: Activationsd
  keys: '@pred'
  sigmoid: true


